services:
  api:
    build:
      context: ./BookTrackerAPI
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=172.31.42.111;Database=BookBuddyDB;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - booktracker-net

  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - booktracker-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - booktracker-net

volumes:
  sqlvolume:

networks:
  booktracker-net:
